services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy:15
        container_name: wg-easy
        networks:
            wg:
                ipv4_address: 10.42.42.42
                ipv6_address: fdcc:ad94:bacf:61a3::2a
            traefik: {}
        volumes:
        - etc_wireguard:/etc/wireguard
        - /lib/modules:/lib/modules:ro
        ports:
        - "51820:51820/udp"
        - "51821:51821/tcp"
        restart: unless-stopped
        cap_add:
        - NET_ADMIN
        - SYS_MODULE
        sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.disable_ipv6=0
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1

    traefik:
        image: traefik:3.3
        container_name: traefik
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443/tcp'
            - '443:443/udp'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/docker/volumes/traefik/traefik.yml:/traefik.yml:ro
            - /etc/docker/volumes/traefik/traefik_dynamic.yml:/traefik_dynamic.yml:ro
            - /etc/docker/volumes/traefik/acme.json:/acme.json
            - /etc/docker/volumes/traefik/cert.pem:/cert.pem:ro
            - /etc/docker/volumes/traefik/private_key.key:/private_key.key:ro
            - /etc/docker/volumes/traefik/traefik_users:/traefik_users:ro
        networks:
            - traefik

volumes:
  etc_wireguard:

networks:
    wg:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
            - subnet: 10.42.42.0/24
            - subnet: fdcc:ad94:bacf:61a3::/64

    traefik:
        external: true
