services:
    traefik:
        image: traefik:3.3
        container_name: traefik
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443/tcp'
            - '443:443/udp'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/docker/volumes/traefik/traefik.yml:/traefik.yml:ro
            - /etc/docker/volumes/traefik/traefik_dynamic.yml:/traefik_dynamic.yml:ro
            - /etc/docker/volumes/traefik/acme.json:/acme.json
            - /etc/docker/volumes/traefik/cert.pem:/cert.pem:ro
            - /etc/docker/volumes/traefik/private_key.key:/private_key.key:ro
            - /etc/docker/volumes/traefik/traefik_users:/traefik_users:ro
        networks:
            - traefik

networks:
    traefik:
        external: true
