---
- name: Provision Ubuntu 22.04 VM
  hosts: webservers
  become: true
  roles:
    - geerlingguy.docker
  remote_user: "{{ admin_user }}"
  vars:
    deploy_user_pub_key_file: "{{ lookup('file', '{{ deploy_user_pub_key_path }}') }}"

  tasks:
    - name: Ensure the deploy user is created
      user:
        name: "{{ deploy_user }}"
        groups:
          - "{{ deploy_user }}"
          - docker
        shell: /bin/bash
        state: present

    - name: Add the public key to the deploy user's authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ deploy_user }}"
        key: "{{ deploy_user_pub_key_file }}"

    - name: Ensure traefik directories
      file:
        path: "{{ item }}"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0700"
        state: directory
      with_items:
        - "{{ traefik_dest_volume_dir }}"
        - "{{ traefik_dest_compose_dir }}"

    - name: Create acme.json
      file:
        path: "{{ traefik_dest_volume_dir }}/acme.json"
        owner: "{{ deploy_user }}"
        mode: "0600"
        state: "touch"

    - name: Copy SSL cert
      copy:
        src: "{{ ssl_certificate_src_path }}"
        dest: "{{ traefik_dest_volume_dir }}/cert.pem"
        owner: "{{ deploy_user }}"

    - name: Copy SSL private key
      copy:
        src: "{{ ssl_private_key_src_path }}"
        dest: "{{ traefik_dest_volume_dir }}/private_key.key"
        owner: "{{ deploy_user }}"

    - name: Ensure wg-easy directory
      file:
        path: "{{ wg_easy_compose_dir }}"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0700"
        state: directory
